// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-cAtUJOFg5E0pdssn5Oef6zTQ146yg4',
    appId: '1:611297016427:web:d8c14a631385c1fa054f2e',
    messagingSenderId: '611297016427',
    projectId: 'boussole-4f2cd',
    authDomain: 'boussole-4f2cd.firebaseapp.com',
    storageBucket: 'boussole-4f2cd.firebasestorage.app',
    measurementId: 'G-BPVKJ2PZY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3U_G8VtLOky-r8AQq7-P9WBiOxSYiSok',
    appId: '1:611297016427:android:16d7640025b3744b054f2e',
    messagingSenderId: '611297016427',
    projectId: 'boussole-4f2cd',
    storageBucket: 'boussole-4f2cd.firebasestorage.app',
  );
}
