import '../../models/companion_moment.dart';

const companionMomentsCatalog = <CompanionMoment>[
  CompanionMoment(
    id: 'idea_object_story',
    title: 'Inventer l’histoire d’un objet',
    shortDescription: 'Choisir un objet proche et imaginer son aventure.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'travel'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'créativité', 'confiance'},
    compatibleInterests: {'jeux imaginaires', 'lecture'},
    tags: {'imaginer', 'histoires', 'jeux imaginaires'},
  ),
  CompanionMoment(
    id: 'idea_three_colors',
    title: 'Chercher trois couleurs',
    shortDescription:
        'Repérer autour de soi trois objets de couleurs différentes.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.observe,
    minimumAge: 3,
    maximumAge: 10,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'curiosité', 'concentration'},
    tags: {'observer', 'jeux calmes'},
  ),
  CompanionMoment(
    id: 'create_protective_dragon',
    title: 'Dessiner un dragon protecteur',
    shortDescription: 'Imaginer un dragon qui protège un lieu merveilleux.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.create,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'waitingRoom', 'rain'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'paper', 'pencils'},
    compatibleParentGoals: {'créativité', 'concentration'},
    compatibleInterests: {'dragons', 'dessin'},
    incompatibleAvoidedActivities: {'dessin'},
    tags: {'dessiner', 'dragons', 'dessin'},
  ),
  CompanionMoment(
    id: 'create_cardboard_robot',
    title: 'Construire un petit robot',
    shortDescription:
        'Assembler quelques éléments recyclés pour créer un robot.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.build,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 20,
    compatibleContexts: {'home', 'rain'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'recycledMaterials', 'tape'},
    compatibleParentGoals: {'créativité', 'autonomie'},
    compatibleInterests: {'construction', 'sciences', 'bricolage'},
    incompatibleAvoidedActivities: {'bricolage', 'activités salissantes'},
    tags: {'construire', 'bricoler', 'robot'},
  ),
  CompanionMoment(
    id: 'move_animal_walks',
    title: 'Marcher comme trois animaux',
    shortDescription: 'Traverser la pièce en imitant trois animaux différents.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.move,
    minimumAge: 3,
    maximumAge: 9,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'confiance', 'créativité'},
    compatibleInterests: {'animaux', 'sport'},
    incompatibleAvoidedActivities: {'activités sportives', 'animaux'},
    incompatibleSensitiveSituations: {'bruit important'},
    tags: {'bouger', 'animaux', 'faire du sport'},
  ),
  CompanionMoment(
    id: 'move_favorite_song',
    title: 'Danser le temps d’une chanson',
    shortDescription:
        'Choisir une chanson et laisser le corps bouger librement.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.dance,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'music'},
    compatibleParentGoals: {'confiance', 'gestion des émotions'},
    compatibleInterests: {'danse', 'musique', 'sport'},
    incompatibleAvoidedActivities: {'musique', 'activités sportives'},
    incompatibleSensitiveSituations: {'bruit important'},
    tags: {'danser', 'musique', 'bouger'},
  ),
  CompanionMoment(
    id: 'calm_five_breaths',
    title: 'Faire cinq respirations tranquilles',
    shortDescription: 'Inspirer doucement puis souffler comme sur une plume.',
    primaryNeed: CompanionNeed.calmDown,
    family: CompanionMomentFamily.relax,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 3,
    compatibleContexts: {'home', 'waitingRoom', 'travel', 'school'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'gestion des émotions', 'concentration'},
    tags: {'respirer calmement', 'calme', 'jeux calmes'},
  ),
  CompanionMoment(
    id: 'calm_read_nook',
    title: 'Lire quelques pages au calme',
    shortDescription:
        'Choisir un livre et s’installer dans un endroit confortable.',
    primaryNeed: CompanionNeed.calmDown,
    family: CompanionMomentFamily.read,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'rain'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'book'},
    compatibleParentGoals: {'concentration', 'gestion des émotions'},
    compatibleInterests: {'lecture'},
    incompatibleAvoidedActivities: {'lecture'},
    tags: {'lire', 'lecture', 'jeux calmes'},
  ),
  CompanionMoment(
    id: 'wait_cloud_shapes',
    title: 'Trouver des formes autour de soi',
    shortDescription: 'Chercher un rond, un carré puis un triangle.',
    primaryNeed: CompanionNeed.wait,
    family: CompanionMomentFamily.observe,
    minimumAge: 3,
    maximumAge: 9,
    durationMinutes: 5,
    compatibleContexts: {'waitingRoom', 'travel', 'outside'},
    compatibleMainMoments: {'waiting', 'travel'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'patience', 'concentration'},
    tags: {'observer', 'patienter'},
  ),
  CompanionMoment(
    id: 'wait_riddle',
    title: 'Inventer une devinette',
    shortDescription:
        'Choisir quelque chose et donner trois indices pour le faire trouver.',
    primaryNeed: CompanionNeed.wait,
    family: CompanionMomentFamily.think,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'waitingRoom', 'travel', 'home'},
    compatibleMainMoments: {'waiting', 'travel'},
    participants: CompanionParticipantContext.withParent,
    compatibleParentGoals: {'patience', 'concentration', 'confiance'},
    tags: {'réfléchir', 'jeux de réflexion'},
  ),
  CompanionMoment(
    id: 'share_family_memory',
    title: 'Raconter un joli souvenir',
    shortDescription: 'Partager chacun un souvenir qui donne le sourire.',
    primaryNeed: CompanionNeed.share,
    family: CompanionMomentFamily.share,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'travel', 'vacation'},
    participants: CompanionParticipantContext.family,
    compatibleParentGoals: {'confiance', 'entraide'},
    tags: {'partager', 'famille', 'parler'},
  ),
  CompanionMoment(
    id: 'share_cooperative_tower',
    title: 'Construire une tour à plusieurs',
    shortDescription:
        'Ajouter chacun une pièce pour faire grandir la même tour.',
    primaryNeed: CompanionNeed.share,
    family: CompanionMomentFamily.build,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'rain'},
    participants: CompanionParticipantContext.withSibling,
    requiredMaterials: {'buildingBlocks'},
    compatibleParentGoals: {'entraide', 'patience'},
    compatibleInterests: {'construction', 'Lego'},
    incompatibleAvoidedActivities: {'bricolage'},
    tags: {'construire', 'partager', 'Lego'},
  ),
  CompanionMoment(
    id: 'help_set_table',
    title: 'Préparer la table ensemble',
    shortDescription: 'Choisir une petite partie de la table à installer.',
    primaryNeed: CompanionNeed.help,
    family: CompanionMomentFamily.help,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home'},
    compatibleMainMoments: {'beforeMeal'},
    participants: CompanionParticipantContext.withParent,
    compatibleParentGoals: {'autonomie', 'responsabilités', 'entraide'},
    compatibleInterests: {'aider à la maison'},
    tags: {'aider', 'aider à la maison', 'autonomie'},
  ),
  CompanionMoment(
    id: 'help_water_plant',
    title: 'Prendre soin d’une plante',
    shortDescription:
        'Vérifier la terre et donner un peu d’eau si elle est sèche.',
    primaryNeed: CompanionNeed.help,
    family: CompanionMomentFamily.garden,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'plant', 'water'},
    compatibleParentGoals: {'autonomie', 'responsabilités'},
    compatibleInterests: {'nature', 'jardin'},
    incompatibleAvoidedActivities: {'nature', 'activités salissantes'},
    tags: {'jardiner', 'nature', 'aider'},
  ),
  CompanionMoment(
    id: 'explore_tiny_nature',
    title: 'Observer un petit coin de nature',
    shortDescription:
        'Regarder attentivement une feuille, une pierre ou un insecte.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.explore,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'curiosité', 'concentration'},
    compatibleInterests: {'nature', 'animaux', 'sciences'},
    incompatibleAvoidedActivities: {'nature', 'animaux'},
    incompatibleSensitiveSituations: {'nouveaux lieux'},
    tags: {'explorer', 'observer la nature', 'nature'},
  ),
  CompanionMoment(
    id: 'explore_home_detective',
    title: 'Devenir détective de la maison',
    shortDescription: 'Trouver trois objets dont on ne connaissait pas le nom.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.observe,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'curiosité', 'autonomie'},
    tags: {'observer', 'explorer', 'maison'},
  ),
  CompanionMoment(
    id: 'learn_float_test',
    title: 'Tester ce qui flotte',
    shortDescription:
        'Avec un parent, comparer quelques objets dans un bol d’eau.',
    primaryNeed: CompanionNeed.learn,
    family: CompanionMomentFamily.experiment,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'bowl', 'water', 'smallObjects'},
    compatibleParentGoals: {'curiosité', 'concentration'},
    compatibleInterests: {'sciences'},
    incompatibleAvoidedActivities: {'activités salissantes'},
    tags: {'expérimenter', 'sciences', 'apprendre'},
  ),
  CompanionMoment(
    id: 'learn_word_hunt',
    title: 'Faire une chasse aux mots',
    shortDescription: 'Trouver cinq mots qui commencent par la même lettre.',
    primaryNeed: CompanionNeed.learn,
    family: CompanionMomentFamily.read,
    minimumAge: 7,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'travel'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'concentration', 'curiosité'},
    compatibleInterests: {'lecture'},
    incompatibleAvoidedActivities: {'lecture'},
    tags: {'lire', 'mots', 'lecture'},
  ),
  CompanionMoment(
    id: 'confidence_small_challenge',
    title: 'Choisir un petit défi réalisable',
    shortDescription:
        'Choisir une chose simple à essayer puis reconnaître l’effort.',
    primaryNeed: CompanionNeed.buildConfidence,
    family: CompanionMomentFamily.play,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.withParent,
    compatibleParentGoals: {'confiance', 'courage'},
    tags: {'confiance', 'courage', 'jouer'},
  ),
  CompanionMoment(
    id: 'confidence_recipe_helper',
    title: 'Réaliser une étape de recette',
    shortDescription:
        'Choisir avec un parent une étape simple à faire soi-même.',
    primaryNeed: CompanionNeed.buildConfidence,
    family: CompanionMomentFamily.cook,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home'},
    compatibleMainMoments: {'beforeMeal', 'freeTime'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'kitchen'},
    compatibleParentGoals: {'confiance', 'autonomie', 'responsabilités'},
    compatibleInterests: {'cuisine'},
    incompatibleAvoidedActivities: {'cuisine', 'activités salissantes'},
    tags: {'cuisiner', 'cuisine', 'autonomie'},
  ),
  CompanionMoment(
    id: 'celebrate_effort_dance',
    title: 'Faire la danse de l’effort',
    shortDescription:
        'Inventer quelques mouvements pour célébrer l’effort accompli.',
    primaryNeed: CompanionNeed.celebrate,
    family: CompanionMomentFamily.celebrate,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.family,
    compatibleParentGoals: {'confiance'},
    compatibleInterests: {'danse', 'musique'},
    incompatibleAvoidedActivities: {'musique', 'activités sportives'},
    incompatibleSensitiveSituations: {'bruit important'},
    tags: {'célébrer', 'danser', 'effort'},
  ),
  CompanionMoment(
    id: 'celebrate_shared_drawing',
    title: 'Créer le dessin d’un beau moment',
    shortDescription:
        'Dessiner ensemble ce que l’on souhaite garder en souvenir.',
    primaryNeed: CompanionNeed.celebrate,
    family: CompanionMomentFamily.share,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'paper', 'pencils'},
    compatibleParentGoals: {'confiance', 'créativité'},
    compatibleInterests: {'dessin'},
    incompatibleAvoidedActivities: {'dessin'},
    tags: {'célébrer', 'dessiner', 'partager'},
  ),
  CompanionMoment(
    id: 'rest_listen_quietly',
    title: 'Écouter les sons tranquilles',
    shortDescription: 'S’installer confortablement et repérer trois sons doux.',
    primaryNeed: CompanionNeed.rest,
    family: CompanionMomentFamily.relax,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'gestion des émotions', 'concentration'},
    tags: {'se détendre', 'jeux calmes', 'écouter'},
  ),
  CompanionMoment(
    id: 'rest_cozy_story',
    title: 'Partager une histoire reposante',
    shortDescription:
        'Choisir une courte histoire et l’écouter confortablement.',
    primaryNeed: CompanionNeed.rest,
    family: CompanionMomentFamily.read,
    minimumAge: 3,
    maximumAge: 10,
    durationMinutes: 10,
    compatibleContexts: {'home', 'rain'},
    compatibleMainMoments: {'beforeBed', 'freeTime'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'book'},
    compatibleParentGoals: {'gestion des émotions'},
    compatibleInterests: {'lecture'},
    incompatibleAvoidedActivities: {'lecture'},
    tags: {'lire', 'lecture', 'se détendre'},
  ),
];
