import '../../models/companion_moment.dart';

final companionMomentsExpansion = List<CompanionMoment>.unmodifiable(
  _seeds.indexed.map((entry) {
    final index = entry.$1;
    final seed = entry.$2;
    const durations = [3, 5, 10, 15, 20, 30];
    const contexts = [
      {'home', 'vacation'},
      {'home', 'rain'},
      {'outside', 'vacation'},
      {'home', 'waitingRoom', 'travel'},
      {'home', 'school'},
    ];
    return CompanionMoment(
      id: seed.id,
      title: seed.title,
      shortDescription: seed.description,
      primaryNeed: _need(seed.family),
      family: seed.family,
      minimumAge: 3 + index % 4,
      maximumAge: 12,
      durationMinutes: durations[index % durations.length],
      compatibleContexts: contexts[index % contexts.length],
      participants: CompanionParticipantContext.alone,
      compatibleParentGoals: {_goal(seed.family)},
      compatibleInterests: {seed.interest},
      tags: {seed.interest, _tag(seed.family)},
    );
  }),
);

CompanionNeed _need(CompanionMomentFamily family) => switch (family) {
  CompanionMomentFamily.move ||
  CompanionMomentFamily.dance => CompanionNeed.move,
  CompanionMomentFamily.observe ||
  CompanionMomentFamily.explore => CompanionNeed.explore,
  CompanionMomentFamily.help => CompanionNeed.help,
  CompanionMomentFamily.share => CompanionNeed.share,
  CompanionMomentFamily.read ||
  CompanionMomentFamily.think => CompanionNeed.learn,
  _ => CompanionNeed.create,
};

String _goal(CompanionMomentFamily family) => switch (family) {
  CompanionMomentFamily.help || CompanionMomentFamily.share => 'entraide',
  CompanionMomentFamily.read || CompanionMomentFamily.think => 'concentration',
  CompanionMomentFamily.move || CompanionMomentFamily.dance => 'confiance',
  CompanionMomentFamily.observe || CompanionMomentFamily.explore => 'curiosité',
  _ => 'créativité',
};

String _tag(CompanionMomentFamily family) => switch (family) {
  CompanionMomentFamily.build => 'construire',
  CompanionMomentFamily.draw || CompanionMomentFamily.create => 'dessiner',
  CompanionMomentFamily.imagine => 'imaginer',
  CompanionMomentFamily.play => 'jouer',
  CompanionMomentFamily.move || CompanionMomentFamily.dance => 'bouger',
  CompanionMomentFamily.observe => 'observer',
  CompanionMomentFamily.explore => 'explorer',
  CompanionMomentFamily.read => 'lire',
  CompanionMomentFamily.think => 'réfléchir',
  CompanionMomentFamily.craft => 'bricoler',
  CompanionMomentFamily.cook => 'cuisiner',
  CompanionMomentFamily.garden => 'jardiner',
  CompanionMomentFamily.help => 'aider',
  CompanionMomentFamily.share => 'partager',
  _ => 'créer',
};

class _MomentSeed {
  const _MomentSeed(
    this.id,
    this.title,
    this.description,
    this.family,
    this.interest,
  );
  final String id;
  final String title;
  final String description;
  final CompanionMomentFamily family;
  final String interest;
}

const _seeds = <_MomentSeed>[
  _MomentSeed(
    'extra_animal_mask',
    'Imaginer un masque d’animal',
    'Choisir ses oreilles, ses couleurs et son expression.',
    CompanionMomentFamily.create,
    'animaux',
  ),
  _MomentSeed(
    'extra_dino_tracks',
    'Dessiner des traces de dinosaure',
    'Inventer trois empreintes et deviner leur propriétaire.',
    CompanionMomentFamily.draw,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_postcard',
    'Créer une carte postale spatiale',
    'Imaginer le paysage envoyé depuis une planète lointaine.',
    CompanionMomentFamily.create,
    'espace',
  ),
  _MomentSeed(
    'extra_nature_crown',
    'Composer une couronne de nature',
    'Observer des formes naturelles déjà tombées et imaginer leur place.',
    CompanionMomentFamily.craft,
    'nature',
  ),
  _MomentSeed(
    'extra_dragon_flag',
    'Créer le drapeau d’un dragon',
    'Choisir un symbole, deux couleurs et une devise positive.',
    CompanionMomentFamily.draw,
    'dragons',
  ),
  _MomentSeed(
    'extra_car_dashboard',
    'Inventer un tableau de bord',
    'Choisir trois boutons étonnants pour une voiture imaginaire.',
    CompanionMomentFamily.create,
    'voitures',
  ),
  _MomentSeed(
    'extra_train_ticket',
    'Créer un billet de train secret',
    'Imaginer sa destination et le nom du voyage.',
    CompanionMomentFamily.draw,
    'trains',
  ),
  _MomentSeed(
    'extra_music_symbol',
    'Dessiner un symbole musical',
    'Transformer un son préféré en formes et en couleurs.',
    CompanionMomentFamily.draw,
    'musique',
  ),
  _MomentSeed(
    'extra_dino_bridge',
    'Construire un pont pour dinosaures',
    'Relier deux zones avec des objets stables déjà disponibles.',
    CompanionMomentFamily.build,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_station',
    'Construire une station spatiale',
    'Assembler plusieurs zones pour accueillir un équipage imaginaire.',
    CompanionMomentFamily.build,
    'espace',
  ),
  _MomentSeed(
    'extra_animal_tunnel',
    'Créer un tunnel pour petit animal',
    'Construire un passage imaginaire avec des objets sûrs.',
    CompanionMomentFamily.build,
    'animaux',
  ),
  _MomentSeed(
    'extra_dragon_nest',
    'Construire un nid de dragon',
    'Préparer un refuge solide pour un œuf imaginaire.',
    CompanionMomentFamily.build,
    'dragons',
  ),
  _MomentSeed(
    'extra_car_garage',
    'Construire un garage miniature',
    'Créer une entrée, une place et une sortie.',
    CompanionMomentFamily.build,
    'voitures',
  ),
  _MomentSeed(
    'extra_train_station',
    'Construire une petite gare',
    'Imaginer le quai, l’horloge et la destination.',
    CompanionMomentFamily.build,
    'trains',
  ),
  _MomentSeed(
    'extra_nature_tower',
    'Construire une tour inspirée d’un arbre',
    'Chercher une base large et des branches imaginaires.',
    CompanionMomentFamily.build,
    'nature',
  ),
  _MomentSeed(
    'extra_science_machine',
    'Construire une machine de chercheur',
    'Assembler des formes et expliquer sa fonction imaginaire.',
    CompanionMomentFamily.build,
    'sciences',
  ),
  _MomentSeed(
    'extra_animal_interview',
    'Imaginer l’interview d’un animal',
    'Trouver trois questions et inventer ses réponses.',
    CompanionMomentFamily.imagine,
    'animaux',
  ),
  _MomentSeed(
    'extra_dino_school',
    'Imaginer une école de dinosaures',
    'Choisir les cours et la récréation des jeunes dinosaures.',
    CompanionMomentFamily.imagine,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_weather',
    'Inventer la météo d’une planète',
    'Imaginer son ciel, son vent et une pluie étonnante.',
    CompanionMomentFamily.imagine,
    'espace',
  ),
  _MomentSeed(
    'extra_dragon_friend',
    'Imaginer un ami pour un dragon',
    'Choisir sa rencontre et leur première aventure.',
    CompanionMomentFamily.imagine,
    'dragons',
  ),
  _MomentSeed(
    'extra_car_city',
    'Inventer une ville pour voitures',
    'Choisir ses routes et trois lieux surprenants.',
    CompanionMomentFamily.imagine,
    'voitures',
  ),
  _MomentSeed(
    'extra_train_story',
    'Imaginer le voyage d’un train',
    'Choisir son départ, un obstacle et son arrivée.',
    CompanionMomentFamily.imagine,
    'trains',
  ),
  _MomentSeed(
    'extra_music_world',
    'Imaginer un monde fait de musique',
    'Inventer ce qui s’y passe quand un son commence.',
    CompanionMomentFamily.imagine,
    'musique',
  ),
  _MomentSeed(
    'extra_book_ending',
    'Inventer une autre fin',
    'Choisir une histoire connue et imaginer une nouvelle dernière scène.',
    CompanionMomentFamily.imagine,
    'lecture',
  ),
  _MomentSeed(
    'extra_animal_mime',
    'Jouer au mime des animaux',
    'Faire reconnaître trois animaux uniquement avec des gestes.',
    CompanionMomentFamily.play,
    'animaux',
  ),
  _MomentSeed(
    'extra_dino_guard',
    'Jouer au gardien des œufs',
    'Imaginer un parcours calme autour de trois œufs invisibles.',
    CompanionMomentFamily.play,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_countdown',
    'Jouer au compte à rebours spatial',
    'Préparer trois gestes puis lancer la fusée imaginaire.',
    CompanionMomentFamily.play,
    'espace',
  ),
  _MomentSeed(
    'extra_dragon_clues',
    'Chercher les indices du dragon',
    'Choisir trois détails autour de soi qui raconteraient son passage.',
    CompanionMomentFamily.play,
    'dragons',
  ),
  _MomentSeed(
    'extra_car_sound',
    'Deviner le véhicule au son',
    'Inventer des sons différents et les faire reconnaître.',
    CompanionMomentFamily.play,
    'voitures',
  ),
  _MomentSeed(
    'extra_train_conductor',
    'Jouer au chef de gare',
    'Annoncer trois destinations avec une voix différente.',
    CompanionMomentFamily.play,
    'trains',
  ),
  _MomentSeed(
    'extra_music_echo',
    'Jouer à l’écho musical',
    'Créer un petit rythme puis essayer de le répéter.',
    CompanionMomentFamily.play,
    'musique',
  ),
  _MomentSeed(
    'extra_science_guess',
    'Jouer aux objets mystères',
    'Décrire une forme ou une matière sans donner son nom.',
    CompanionMomentFamily.play,
    'sciences',
  ),
  _MomentSeed(
    'extra_animal_moves',
    'Enchaîner quatre mouvements d’animaux',
    'Changer de démarche à chaque nouveau signal.',
    CompanionMomentFamily.move,
    'animaux',
  ),
  _MomentSeed(
    'extra_dino_race',
    'Faire la course au ralenti des dinosaures',
    'Avancer lentement avec de très grands pas contrôlés.',
    CompanionMomentFamily.move,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_walk',
    'Tester la marche sur la Lune',
    'Faire des mouvements lents et légers dans un espace dégagé.',
    CompanionMomentFamily.move,
    'espace',
  ),
  _MomentSeed(
    'extra_dragon_wings',
    'Bouger comme un dragon en vol',
    'Inventer trois mouvements d’ailes doux et différents.',
    CompanionMomentFamily.move,
    'dragons',
  ),
  _MomentSeed(
    'extra_car_pitstop',
    'Faire un relais de mécanicien',
    'Mimer trois gestes rapides d’un arrêt au stand.',
    CompanionMomentFamily.move,
    'voitures',
  ),
  _MomentSeed(
    'extra_train_rhythm',
    'Suivre le rythme d’un train',
    'Alterner des pas lents puis rapides comme un voyage.',
    CompanionMomentFamily.move,
    'trains',
  ),
  _MomentSeed(
    'extra_music_dance',
    'Inventer une danse de trois gestes',
    'Choisir un début, un milieu et une pose finale.',
    CompanionMomentFamily.dance,
    'musique',
  ),
  _MomentSeed(
    'extra_sport_balance',
    'Créer un défi d’équilibre',
    'Choisir une position sûre et compter quelques secondes.',
    CompanionMomentFamily.move,
    'sport',
  ),
  _MomentSeed(
    'extra_animal_patterns',
    'Observer les motifs des animaux',
    'Chercher autour de soi rayures, taches et écailles imaginaires.',
    CompanionMomentFamily.observe,
    'animaux',
  ),
  _MomentSeed(
    'extra_dino_sizes',
    'Comparer des tailles de dinosaures',
    'Choisir trois objets pour représenter petit, moyen et géant.',
    CompanionMomentFamily.observe,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_sky',
    'Observer un morceau de ciel',
    'Repérer sa couleur, sa lumière et une forme visible.',
    CompanionMomentFamily.observe,
    'espace',
  ),
  _MomentSeed(
    'extra_nature_texture',
    'Explorer trois textures naturelles',
    'Comparer avec les yeux des surfaces différentes sans les abîmer.',
    CompanionMomentFamily.explore,
    'nature',
  ),
  _MomentSeed(
    'extra_car_shapes',
    'Observer les formes des véhicules',
    'Chercher roues, fenêtres et lignes dans son environnement.',
    CompanionMomentFamily.observe,
    'voitures',
  ),
  _MomentSeed(
    'extra_train_route',
    'Explorer un trajet imaginaire',
    'Choisir trois repères qui pourraient devenir des gares.',
    CompanionMomentFamily.explore,
    'trains',
  ),
  _MomentSeed(
    'extra_science_light',
    'Observer les jeux de lumière',
    'Chercher un reflet, une ombre et une zone lumineuse.',
    CompanionMomentFamily.observe,
    'sciences',
  ),
  _MomentSeed(
    'extra_nature_micro',
    'Explorer un tout petit paysage',
    'Regarder de près un coin sûr comme s’il était immense.',
    CompanionMomentFamily.explore,
    'nature',
  ),
  _MomentSeed(
    'extra_animal_book',
    'Chercher un animal dans un livre',
    'Observer une image puis raconter un détail remarqué.',
    CompanionMomentFamily.read,
    'lecture',
  ),
  _MomentSeed(
    'extra_dino_words',
    'Trouver cinq mots de dinosaures',
    'Choisir des mots qui racontent leur monde.',
    CompanionMomentFamily.think,
    'dinosaures',
  ),
  _MomentSeed(
    'extra_space_alphabet',
    'Créer l’alphabet d’une planète',
    'Inventer trois signes et le son associé.',
    CompanionMomentFamily.write,
    'espace',
  ),
  _MomentSeed(
    'extra_dragon_riddle',
    'Résoudre une énigme de dragon',
    'Inventer trois indices menant à un trésor imaginaire.',
    CompanionMomentFamily.think,
    'dragons',
  ),
  _MomentSeed(
    'extra_train_read',
    'Lire comme dans un train',
    'Choisir quelques pages et imaginer le paysage qui défile.',
    CompanionMomentFamily.read,
    'trains',
  ),
  _MomentSeed(
    'extra_science_question',
    'Inventer trois questions de chercheur',
    'Observer un objet puis demander comment, pourquoi et quoi.',
    CompanionMomentFamily.think,
    'sciences',
  ),
  _MomentSeed(
    'extra_music_words',
    'Trouver des mots qui sonnent bien',
    'Choisir trois mots et les dire avec différents rythmes.',
    CompanionMomentFamily.think,
    'musique',
  ),
  _MomentSeed(
    'extra_book_clue',
    'Chercher un indice dans une illustration',
    'Observer une page et imaginer ce qu’un détail annonce.',
    CompanionMomentFamily.read,
    'lecture',
  ),
  _MomentSeed(
    'extra_kitchen_colors',
    'Composer une idée de goûter coloré',
    'Avec un parent, choisir trois couleurs à réunir plus tard.',
    CompanionMomentFamily.cook,
    'cuisine',
  ),
  _MomentSeed(
    'extra_kitchen_menu',
    'Imaginer le menu d’un explorateur',
    'Choisir un nom amusant pour trois plats imaginaires.',
    CompanionMomentFamily.cook,
    'cuisine',
  ),
  _MomentSeed(
    'extra_craft_vehicle',
    'Fabriquer le plan d’un véhicule',
    'Dessiner ou décrire les pièces à assembler avec un parent.',
    CompanionMomentFamily.craft,
    'bricolage',
  ),
  _MomentSeed(
    'extra_craft_music',
    'Créer un instrument imaginaire',
    'Choisir sa forme, son son et la manière d’en jouer.',
    CompanionMomentFamily.craft,
    'musique',
  ),
  _MomentSeed(
    'extra_garden_seed',
    'Imaginer le voyage d’une graine',
    'Raconter ses étapes de la terre jusqu’à la plante.',
    CompanionMomentFamily.garden,
    'jardin',
  ),
  _MomentSeed(
    'extra_garden_shapes',
    'Observer les formes du jardin',
    'Chercher une ligne, une spirale et une étoile naturelle.',
    CompanionMomentFamily.garden,
    'nature',
  ),
  _MomentSeed(
    'extra_help_books',
    'Préparer un coin pour les livres',
    'Choisir une petite amélioration simple pour mieux les retrouver.',
    CompanionMomentFamily.help,
    'lecture',
  ),
  _MomentSeed(
    'extra_share_discovery',
    'Partager une découverte du jour',
    'Choisir un détail intéressant à raconter à quelqu’un.',
    CompanionMomentFamily.share,
    'sciences',
  ),
];
