import '../../models/companion_moment.dart';
import 'companion_moments_expansion.dart';

final companionMomentsCatalog = <CompanionMoment>[
  ..._baseCompanionMomentsCatalog,
  ...companionMomentsExpansion,
];

const _baseCompanionMomentsCatalog = <CompanionMoment>[
  CompanionMoment(
    id: 'generic_observe_nearby',
    title: 'Observer trois choses autour de soi',
    shortDescription: 'Choisir trois objets et remarquer un détail sur chacun.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.observe,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 3,
    compatibleContexts: {
      'home',
      'outside',
      'waitingRoom',
      'travel',
      'school',
      'vacation',
      'rain',
    },
    participants: CompanionParticipantContext.alone,
    tags: {'generic-safe', 'observer'},
  ),
  CompanionMoment(
    id: 'generic_short_story',
    title: 'Imaginer une histoire éclair',
    shortDescription:
        'Choisir un objet et imaginer en quelques phrases son aventure.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'waitingRoom', 'travel', 'school', 'vacation'},
    participants: CompanionParticipantContext.alone,
    tags: {'generic-safe', 'imaginer'},
  ),
  CompanionMoment(
    id: 'generic_small_help',
    title: 'Choisir une petite mission d’aide',
    shortDescription:
        'Repérer une chose simple à ranger ou à préparer autour de soi.',
    primaryNeed: CompanionNeed.help,
    family: CompanionMomentFamily.help,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'school', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'autonomie', 'responsabilités', 'entraide'},
    tags: {'generic-safe', 'aider', 'autonomie'},
  ),
  CompanionMoment(
    id: 'generic_quiet_pause',
    title: 'Faire une petite pause calme',
    shortDescription:
        'S’installer confortablement et écouter les sons autour de soi.',
    primaryNeed: CompanionNeed.calmDown,
    family: CompanionMomentFamily.relax,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 3,
    compatibleContexts: {
      'home',
      'outside',
      'waitingRoom',
      'travel',
      'school',
      'vacation',
    },
    participants: CompanionParticipantContext.alone,
    tags: {'generic-safe', 'calme'},
  ),
  CompanionMoment(
    id: 'generic_one_minute_move',
    title: 'Bouger pendant une minute',
    shortDescription:
        'Choisir quelques mouvements doux et les faire à son rythme.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.move,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 2,
    compatibleContexts: {'home', 'outside', 'school', 'vacation'},
    participants: CompanionParticipantContext.alone,
    tags: {'generic-safe', 'bouger'},
  ),
  CompanionMoment(
    id: 'generic_color_hunt',
    title: 'Chercher une couleur autour de soi',
    shortDescription:
        'Choisir une couleur puis trouver trois choses qui la portent.',
    primaryNeed: CompanionNeed.wait,
    family: CompanionMomentFamily.observe,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 3,
    compatibleContexts: {
      'home',
      'outside',
      'waitingRoom',
      'travel',
      'school',
      'vacation',
    },
    participants: CompanionParticipantContext.alone,
    tags: {'generic-safe', 'observer', 'patienter'},
  ),
  CompanionMoment(
    id: 'idea_object_story',
    title: 'Inventer l’histoire d’un objet',
    shortDescription: 'Choisir un objet proche et imaginer son aventure.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'travel'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'créativité', 'confiance'},
    compatibleInterests: {'jeux imaginaires', 'lecture'},
    tags: {'imaginer', 'histoires', 'jeux imaginaires'},
  ),
  CompanionMoment(
    id: 'idea_three_colors',
    title: 'Chercher trois couleurs',
    shortDescription:
        'Repérer autour de soi trois objets de couleurs différentes.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.observe,
    minimumAge: 3,
    maximumAge: 10,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'curiosité', 'concentration'},
    tags: {'observer', 'jeux calmes'},
  ),
  CompanionMoment(
    id: 'create_protective_dragon',
    title: 'Dessiner un dragon protecteur',
    shortDescription: 'Imaginer un dragon qui protège un lieu merveilleux.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.create,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'waitingRoom', 'rain'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'paper', 'pencils'},
    compatibleParentGoals: {'créativité', 'concentration'},
    compatibleInterests: {'dragons', 'dessin'},
    incompatibleAvoidedActivities: {'dessin'},
    tags: {'dessiner', 'dragons', 'dessin'},
  ),
  CompanionMoment(
    id: 'create_cardboard_robot',
    title: 'Construire un petit robot',
    shortDescription:
        'Assembler quelques éléments recyclés pour créer un robot.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.build,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 20,
    compatibleContexts: {'home', 'rain'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'recycledMaterials', 'tape'},
    compatibleParentGoals: {'créativité', 'autonomie'},
    compatibleInterests: {'construction', 'sciences', 'bricolage'},
    incompatibleAvoidedActivities: {'bricolage', 'activités salissantes'},
    tags: {'construire', 'bricoler', 'robot'},
  ),
  CompanionMoment(
    id: 'move_animal_walks',
    title: 'Marcher comme trois animaux',
    shortDescription: 'Traverser la pièce en imitant trois animaux différents.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.move,
    minimumAge: 3,
    maximumAge: 9,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'confiance', 'créativité'},
    compatibleInterests: {'animaux', 'sport'},
    incompatibleAvoidedActivities: {'activités sportives', 'animaux'},
    incompatibleSensitiveSituations: {'bruit important'},
    tags: {'bouger', 'animaux', 'faire du sport'},
  ),
  CompanionMoment(
    id: 'move_favorite_song',
    title: 'Danser le temps d’une chanson',
    shortDescription:
        'Choisir une chanson et laisser le corps bouger librement.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.dance,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'music'},
    compatibleParentGoals: {'confiance', 'gestion des émotions'},
    compatibleInterests: {'danse', 'musique', 'sport'},
    incompatibleAvoidedActivities: {'musique', 'activités sportives'},
    incompatibleSensitiveSituations: {'bruit important'},
    tags: {'danser', 'musique', 'bouger'},
  ),
  CompanionMoment(
    id: 'calm_five_breaths',
    title: 'Faire cinq respirations tranquilles',
    shortDescription: 'Inspirer doucement puis souffler comme sur une plume.',
    primaryNeed: CompanionNeed.calmDown,
    family: CompanionMomentFamily.relax,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 3,
    compatibleContexts: {'home', 'waitingRoom', 'travel', 'school'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'gestion des émotions', 'concentration'},
    tags: {'respirer calmement', 'calme', 'jeux calmes'},
  ),
  CompanionMoment(
    id: 'calm_read_nook',
    title: 'Lire quelques pages au calme',
    shortDescription:
        'Choisir un livre et s’installer dans un endroit confortable.',
    primaryNeed: CompanionNeed.calmDown,
    family: CompanionMomentFamily.read,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'rain'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'book'},
    compatibleParentGoals: {'concentration', 'gestion des émotions'},
    compatibleInterests: {'lecture'},
    incompatibleAvoidedActivities: {'lecture'},
    tags: {'lire', 'lecture', 'jeux calmes'},
  ),
  CompanionMoment(
    id: 'wait_cloud_shapes',
    title: 'Trouver des formes autour de soi',
    shortDescription: 'Chercher un rond, un carré puis un triangle.',
    primaryNeed: CompanionNeed.wait,
    family: CompanionMomentFamily.observe,
    minimumAge: 3,
    maximumAge: 9,
    durationMinutes: 5,
    compatibleContexts: {'waitingRoom', 'travel', 'outside'},
    compatibleMainMoments: {'waiting', 'travel'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'patience', 'concentration'},
    tags: {'observer', 'patienter'},
  ),
  CompanionMoment(
    id: 'wait_riddle',
    title: 'Inventer une devinette',
    shortDescription:
        'Choisir quelque chose et donner trois indices pour le faire trouver.',
    primaryNeed: CompanionNeed.wait,
    family: CompanionMomentFamily.think,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'waitingRoom', 'travel', 'home'},
    compatibleMainMoments: {'waiting', 'travel'},
    participants: CompanionParticipantContext.withParent,
    compatibleParentGoals: {'patience', 'concentration', 'confiance'},
    tags: {'réfléchir', 'jeux de réflexion'},
  ),
  CompanionMoment(
    id: 'share_family_memory',
    title: 'Raconter un joli souvenir',
    shortDescription: 'Partager chacun un souvenir qui donne le sourire.',
    primaryNeed: CompanionNeed.share,
    family: CompanionMomentFamily.share,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'travel', 'vacation'},
    participants: CompanionParticipantContext.family,
    compatibleParentGoals: {'confiance', 'entraide'},
    tags: {'partager', 'famille', 'parler'},
  ),
  CompanionMoment(
    id: 'share_cooperative_tower',
    title: 'Construire une tour à plusieurs',
    shortDescription:
        'Ajouter chacun une pièce pour faire grandir la même tour.',
    primaryNeed: CompanionNeed.share,
    family: CompanionMomentFamily.build,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'rain'},
    participants: CompanionParticipantContext.withSibling,
    requiredMaterials: {'buildingBlocks'},
    compatibleParentGoals: {'entraide', 'patience'},
    compatibleInterests: {'construction', 'Lego'},
    incompatibleAvoidedActivities: {'bricolage'},
    tags: {'construire', 'partager', 'Lego'},
  ),
  CompanionMoment(
    id: 'help_set_table',
    title: 'Préparer la table ensemble',
    shortDescription: 'Choisir une petite partie de la table à installer.',
    primaryNeed: CompanionNeed.help,
    family: CompanionMomentFamily.help,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home'},
    compatibleMainMoments: {'beforeMeal'},
    participants: CompanionParticipantContext.withParent,
    compatibleParentGoals: {'autonomie', 'responsabilités', 'entraide'},
    compatibleInterests: {'aider à la maison'},
    tags: {'aider', 'aider à la maison', 'autonomie'},
  ),
  CompanionMoment(
    id: 'help_water_plant',
    title: 'Prendre soin d’une plante',
    shortDescription:
        'Vérifier la terre et donner un peu d’eau si elle est sèche.',
    primaryNeed: CompanionNeed.help,
    family: CompanionMomentFamily.garden,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    requiredMaterials: {'plant', 'water'},
    compatibleParentGoals: {'autonomie', 'responsabilités'},
    compatibleInterests: {'nature', 'jardin'},
    incompatibleAvoidedActivities: {'nature', 'activités salissantes'},
    tags: {'jardiner', 'nature', 'aider'},
  ),
  CompanionMoment(
    id: 'explore_tiny_nature',
    title: 'Observer un petit coin de nature',
    shortDescription:
        'Regarder attentivement une feuille, une pierre ou un insecte.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.explore,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'curiosité', 'concentration'},
    compatibleInterests: {'nature', 'animaux', 'sciences'},
    incompatibleAvoidedActivities: {'nature', 'animaux'},
    incompatibleSensitiveSituations: {'nouveaux lieux'},
    tags: {'explorer', 'observer la nature', 'nature'},
  ),
  CompanionMoment(
    id: 'explore_home_detective',
    title: 'Devenir détective de la maison',
    shortDescription: 'Trouver trois objets dont on ne connaissait pas le nom.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.observe,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'curiosité', 'autonomie'},
    tags: {'observer', 'explorer', 'maison'},
  ),
  CompanionMoment(
    id: 'learn_float_test',
    title: 'Tester ce qui flotte',
    shortDescription:
        'Avec un parent, comparer quelques objets dans un bol d’eau.',
    primaryNeed: CompanionNeed.learn,
    family: CompanionMomentFamily.experiment,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'bowl', 'water', 'smallObjects'},
    compatibleParentGoals: {'curiosité', 'concentration'},
    compatibleInterests: {'sciences'},
    incompatibleAvoidedActivities: {'activités salissantes'},
    tags: {'expérimenter', 'sciences', 'apprendre'},
  ),
  CompanionMoment(
    id: 'learn_word_hunt',
    title: 'Faire une chasse aux mots',
    shortDescription: 'Trouver cinq mots qui commencent par la même lettre.',
    primaryNeed: CompanionNeed.learn,
    family: CompanionMomentFamily.read,
    minimumAge: 7,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'travel'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'concentration', 'curiosité'},
    compatibleInterests: {'lecture'},
    incompatibleAvoidedActivities: {'lecture'},
    tags: {'lire', 'mots', 'lecture'},
  ),
  CompanionMoment(
    id: 'confidence_small_challenge',
    title: 'Choisir un petit défi réalisable',
    shortDescription:
        'Choisir une chose simple à essayer puis reconnaître l’effort.',
    primaryNeed: CompanionNeed.buildConfidence,
    family: CompanionMomentFamily.play,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.withParent,
    compatibleParentGoals: {'confiance', 'courage'},
    tags: {'confiance', 'courage', 'jouer'},
  ),
  CompanionMoment(
    id: 'confidence_recipe_helper',
    title: 'Réaliser une étape de recette',
    shortDescription:
        'Choisir avec un parent une étape simple à faire soi-même.',
    primaryNeed: CompanionNeed.buildConfidence,
    family: CompanionMomentFamily.cook,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home'},
    compatibleMainMoments: {'beforeMeal', 'freeTime'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'kitchen'},
    compatibleParentGoals: {'confiance', 'autonomie', 'responsabilités'},
    compatibleInterests: {'cuisine'},
    incompatibleAvoidedActivities: {'cuisine', 'activités salissantes'},
    tags: {'cuisiner', 'cuisine', 'autonomie'},
  ),
  CompanionMoment(
    id: 'celebrate_effort_dance',
    title: 'Faire la danse de l’effort',
    shortDescription:
        'Inventer quelques mouvements pour célébrer l’effort accompli.',
    primaryNeed: CompanionNeed.celebrate,
    family: CompanionMomentFamily.celebrate,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.family,
    compatibleParentGoals: {'confiance'},
    compatibleInterests: {'danse', 'musique'},
    incompatibleAvoidedActivities: {'musique', 'activités sportives'},
    incompatibleSensitiveSituations: {'bruit important'},
    tags: {'célébrer', 'danser', 'effort'},
  ),
  CompanionMoment(
    id: 'celebrate_shared_drawing',
    title: 'Créer le dessin d’un beau moment',
    shortDescription:
        'Dessiner ensemble ce que l’on souhaite garder en souvenir.',
    primaryNeed: CompanionNeed.celebrate,
    family: CompanionMomentFamily.share,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'paper', 'pencils'},
    compatibleParentGoals: {'confiance', 'créativité'},
    compatibleInterests: {'dessin'},
    incompatibleAvoidedActivities: {'dessin'},
    tags: {'célébrer', 'dessiner', 'partager'},
  ),
  CompanionMoment(
    id: 'rest_listen_quietly',
    title: 'Écouter les sons tranquilles',
    shortDescription: 'S’installer confortablement et repérer trois sons doux.',
    primaryNeed: CompanionNeed.rest,
    family: CompanionMomentFamily.relax,
    minimumAge: 3,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'gestion des émotions', 'concentration'},
    tags: {'se détendre', 'jeux calmes', 'écouter'},
  ),
  CompanionMoment(
    id: 'rest_cozy_story',
    title: 'Partager une histoire reposante',
    shortDescription:
        'Choisir une courte histoire et l’écouter confortablement.',
    primaryNeed: CompanionNeed.rest,
    family: CompanionMomentFamily.read,
    minimumAge: 3,
    maximumAge: 10,
    durationMinutes: 10,
    compatibleContexts: {'home', 'rain'},
    compatibleMainMoments: {'beforeBed', 'freeTime'},
    participants: CompanionParticipantContext.withParent,
    requiredMaterials: {'book'},
    compatibleParentGoals: {'gestion des émotions'},
    compatibleInterests: {'lecture'},
    incompatibleAvoidedActivities: {'lecture'},
    tags: {'lire', 'lecture', 'se détendre'},
  ),
  CompanionMoment(
    id: 'create_dinosaur_portrait',
    title: 'Dessiner le portrait d’un dinosaure',
    shortDescription:
        'Imaginer ses écailles, ses couleurs et son drôle de regard.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.draw,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'rain', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'dinosaures', 'dessin'},
    tags: {'dessiner', 'dinosaures', 'créativité'},
  ),
  CompanionMoment(
    id: 'create_space_planet',
    title: 'Inventer une planète colorée',
    shortDescription:
        'Dessiner une planète et choisir ce qui pousse à sa surface.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.draw,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'rain', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'espace', 'dessin', 'sciences'},
    tags: {'dessiner', 'espace', 'planète'},
  ),
  CompanionMoment(
    id: 'create_animal_badge',
    title: 'Créer l’emblème d’un animal',
    shortDescription: 'Choisir un animal et inventer son signe secret.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.draw,
    minimumAge: 4,
    maximumAge: 11,
    durationMinutes: 10,
    compatibleContexts: {'home', 'waitingRoom', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'animaux', 'dessin'},
    tags: {'dessiner', 'animaux', 'imaginer'},
  ),
  CompanionMoment(
    id: 'create_pirate_map',
    title: 'Tracer une carte au trésor',
    shortDescription:
        'Placer une île, trois obstacles et une cachette secrète.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.draw,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 20,
    compatibleContexts: {'home', 'rain', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'pirates', 'dessin'},
    tags: {'dessiner', 'pirates', 'carte'},
  ),
  CompanionMoment(
    id: 'create_dragon_comic',
    title: 'Créer une mini BD de dragon',
    shortDescription:
        'Imaginer trois images pour raconter une aventure de dragon.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.create,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 20,
    compatibleContexts: {'home', 'rain'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'dragons', 'dessin'},
    tags: {'dessiner', 'dragons', 'histoires'},
  ),
  CompanionMoment(
    id: 'create_car_design',
    title: 'Imaginer la voiture du futur',
    shortDescription:
        'Choisir trois fonctions étonnantes pour une nouvelle voiture.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.create,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'travel', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'voitures', 'sciences'},
    tags: {'voitures', 'imaginer', 'inventer'},
  ),
  CompanionMoment(
    id: 'create_music_cover',
    title: 'Inventer la pochette d’une chanson',
    shortDescription:
        'Choisir des formes et des couleurs qui racontent une musique.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.create,
    minimumAge: 7,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'rain'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'musique', 'dessin'},
    tags: {'musique', 'dessiner', 'créativité'},
  ),
  CompanionMoment(
    id: 'build_dinosaur_skeleton',
    title: 'Construire un squelette de dinosaure',
    shortDescription:
        'Assembler des objets allongés pour former un dinosaure au sol.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.build,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 20,
    compatibleContexts: {'home', 'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'dinosaures', 'construction'},
    tags: {'construire', 'dinosaures'},
  ),
  CompanionMoment(
    id: 'build_space_rocket',
    title: 'Construire une fusée miniature',
    shortDescription:
        'Assembler quelques objets légers pour préparer un voyage spatial.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.build,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 20,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'espace', 'construction', 'Lego'},
    tags: {'construire', 'espace', 'fusée'},
  ),
  CompanionMoment(
    id: 'build_animal_shelter',
    title: 'Construire un refuge pour un animal imaginaire',
    shortDescription: 'Créer un petit abri avec des objets déjà disponibles.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.build,
    minimumAge: 4,
    maximumAge: 11,
    durationMinutes: 15,
    compatibleContexts: {'home', 'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'animaux', 'construction', 'nature'},
    tags: {'construire', 'animaux'},
  ),
  CompanionMoment(
    id: 'build_tall_tower',
    title: 'Construire la plus haute tour possible',
    shortDescription:
        'Empiler des objets stables puis observer ce qui la rend solide.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.build,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'construction', 'Lego'},
    tags: {'construire', 'équilibre'},
  ),
  CompanionMoment(
    id: 'build_bridge_challenge',
    title: 'Créer un pont entre deux objets',
    shortDescription:
        'Chercher une façon stable de relier deux supports proches.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.build,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'construction', 'sciences', 'Lego'},
    tags: {'construire', 'réfléchir'},
  ),
  CompanionMoment(
    id: 'build_cozy_cabin',
    title: 'Préparer une petite cabane confortable',
    shortDescription:
        'Choisir un coin et créer un refuge avec ce qui est autorisé.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.build,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 30,
    compatibleContexts: {'home', 'vacation', 'rain'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'construction', 'jeux imaginaires'},
    tags: {'construire', 'cabane', 'imaginer'},
  ),
  CompanionMoment(
    id: 'imagine_dinosaur_day',
    title: 'Imaginer la journée d’un dinosaure',
    shortDescription: 'Choisir où il va, ce qu’il mange et qui il rencontre.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 4,
    maximumAge: 10,
    durationMinutes: 10,
    compatibleContexts: {'home', 'travel', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'dinosaures', 'jeux imaginaires'},
    tags: {'dinosaures', 'imaginer', 'histoires'},
  ),
  CompanionMoment(
    id: 'imagine_space_message',
    title: 'Inventer un message venu de l’espace',
    shortDescription:
        'Imaginer trois mots extraterrestres et leur signification.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'travel', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'espace', 'sciences'},
    tags: {'espace', 'imaginer', 'mots'},
  ),
  CompanionMoment(
    id: 'imagine_animal_power',
    title: 'Choisir un pouvoir d’animal',
    shortDescription:
        'Imaginer quel pouvoir un animal pourrait partager pour une journée.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 4,
    maximumAge: 11,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside', 'travel', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'animaux', 'jeux imaginaires'},
    tags: {'animaux', 'imaginer'},
  ),
  CompanionMoment(
    id: 'imagine_secret_train',
    title: 'Inventer la destination d’un train secret',
    shortDescription:
        'Choisir trois arrêts étonnants et ce que l’on y découvre.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.imagine,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'travel', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'trains', 'jeux imaginaires'},
    tags: {'trains', 'imaginer', 'explorer'},
  ),
  CompanionMoment(
    id: 'play_animal_guess',
    title: 'Faire deviner un animal sans parler',
    shortDescription:
        'Choisir ses gestes les plus reconnaissables pour le faire trouver.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.play,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'outside', 'vacation'},
    participants: CompanionParticipantContext.withParent,
    compatibleInterests: {'animaux', 'jeux imaginaires'},
    tags: {'jouer', 'animaux', 'mimer'},
  ),
  CompanionMoment(
    id: 'play_room_detective',
    title: 'Jouer au détective des détails',
    shortDescription:
        'Observer la pièce, fermer les yeux puis retrouver ce qui a changé.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.play,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.withParent,
    compatibleInterests: {'jeux de réflexion', 'sciences'},
    tags: {'jouer', 'observer', 'réfléchir'},
  ),
  CompanionMoment(
    id: 'play_pirate_balance',
    title: 'Traverser le pont des pirates',
    shortDescription: 'Suivre une ligne au sol en gardant son équilibre.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.play,
    minimumAge: 4,
    maximumAge: 10,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'pirates', 'sport'},
    tags: {'jouer', 'pirates', 'bouger'},
  ),
  CompanionMoment(
    id: 'play_shadow_shapes',
    title: 'Créer des formes avec son ombre',
    shortDescription:
        'Chercher trois silhouettes amusantes avec ses mains ou son corps.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.play,
    minimumAge: 3,
    maximumAge: 10,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'jeux imaginaires', 'animaux'},
    tags: {'jouer', 'imaginer', 'ombres'},
  ),
  CompanionMoment(
    id: 'play_sound_sequence',
    title: 'Inventer un code de trois sons',
    shortDescription:
        'Créer une petite suite de sons puis essayer de la reproduire.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.play,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'musique', 'jeux de réflexion'},
    tags: {'jouer', 'musique', 'mémoire'},
  ),
  CompanionMoment(
    id: 'move_dinosaur_steps',
    title: 'Tester trois marches de dinosaures',
    shortDescription: 'Comparer les pas d’un petit, d’un rapide et d’un géant.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.move,
    minimumAge: 3,
    maximumAge: 9,
    durationMinutes: 5,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'dinosaures', 'sport'},
    tags: {'bouger', 'dinosaures'},
  ),
  CompanionMoment(
    id: 'move_space_training',
    title: 'Faire l’entraînement d’un astronaute',
    shortDescription: 'Enchaîner trois mouvements lents comme dans l’espace.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.move,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'espace', 'sport'},
    tags: {'bouger', 'espace'},
  ),
  CompanionMoment(
    id: 'move_color_course',
    title: 'Créer un parcours de couleurs',
    shortDescription:
        'Choisir trois couleurs visibles et se déplacer de l’une à l’autre.',
    primaryNeed: CompanionNeed.move,
    family: CompanionMomentFamily.move,
    minimumAge: 4,
    maximumAge: 10,
    durationMinutes: 10,
    compatibleContexts: {'home', 'outside'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'sport', 'dessin'},
    tags: {'bouger', 'couleurs'},
  ),
  CompanionMoment(
    id: 'observe_bird_clues',
    title: 'Chercher les indices des oiseaux',
    shortDescription:
        'Écouter, regarder et repérer trois signes de leur présence.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.observe,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'animaux', 'nature'},
    tags: {'observer', 'oiseaux', 'animaux', 'nature'},
  ),
  CompanionMoment(
    id: 'explore_home_shapes',
    title: 'Explorer les formes de la maison',
    shortDescription:
        'Trouver un cercle, un rectangle et une forme inattendue.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.explore,
    minimumAge: 3,
    maximumAge: 10,
    durationMinutes: 5,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'sciences', 'construction'},
    tags: {'explorer', 'observer', 'formes'},
  ),
  CompanionMoment(
    id: 'read_character_voice',
    title: 'Lire avec une voix de personnage',
    shortDescription: 'Choisir un court passage et inventer une voix amusante.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.read,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'vacation', 'rain'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'lecture', 'jeux imaginaires'},
    tags: {'lire', 'lecture', 'imaginer'},
  ),
  CompanionMoment(
    id: 'think_dinosaur_riddle',
    title: 'Inventer une devinette de dinosaure',
    shortDescription:
        'Choisir un dinosaure et trouver trois indices pour le reconnaître.',
    primaryNeed: CompanionNeed.findIdea,
    family: CompanionMomentFamily.think,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 10,
    compatibleContexts: {'home', 'travel', 'waitingRoom'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'dinosaures', 'jeux de réflexion'},
    tags: {'réfléchir', 'dinosaures', 'devinette'},
  ),
  CompanionMoment(
    id: 'share_kind_idea',
    title: 'Préparer une petite attention',
    shortDescription:
        'Choisir un geste simple qui pourrait faire plaisir à quelqu’un.',
    primaryNeed: CompanionNeed.share,
    family: CompanionMomentFamily.share,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 5,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleParentGoals: {'entraide', 'autonomie'},
    tags: {'partager', 'aider'},
  ),
  CompanionMoment(
    id: 'craft_nature_pattern',
    title: 'Composer un motif de nature',
    shortDescription:
        'Aligner quelques éléments déjà tombés pour créer un motif.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.craft,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'nature', 'bricolage'},
    tags: {'bricoler', 'nature', 'créer'},
  ),
  CompanionMoment(
    id: 'cook_snack_plan',
    title: 'Imaginer une assiette rigolote',
    shortDescription:
        'Avec un parent, choisir comment disposer un goûter simple.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.cook,
    minimumAge: 5,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'home', 'vacation'},
    participants: CompanionParticipantContext.withParent,
    compatibleInterests: {'cuisine'},
    tags: {'cuisiner', 'cuisine', 'créer'},
  ),
  CompanionMoment(
    id: 'craft_cardboard_creature',
    title: 'Inventer une créature en carton',
    shortDescription:
        'Avec un parent, transformer un petit emballage propre en personnage.',
    primaryNeed: CompanionNeed.create,
    family: CompanionMomentFamily.craft,
    minimumAge: 6,
    maximumAge: 12,
    durationMinutes: 25,
    compatibleContexts: {'home', 'vacation', 'rain'},
    participants: CompanionParticipantContext.withParent,
    compatibleInterests: {'bricolage', 'animaux', 'jeux imaginaires'},
    tags: {'bricoler', 'créer', 'imaginer'},
  ),
  CompanionMoment(
    id: 'garden_leaf_colors',
    title: 'Créer un nuancier de feuilles',
    shortDescription:
        'Observer des feuilles déjà tombées et les classer par couleur.',
    primaryNeed: CompanionNeed.explore,
    family: CompanionMomentFamily.garden,
    minimumAge: 4,
    maximumAge: 12,
    durationMinutes: 15,
    compatibleContexts: {'outside', 'vacation'},
    participants: CompanionParticipantContext.alone,
    compatibleInterests: {'jardin', 'nature', 'sciences'},
    tags: {'jardiner', 'nature', 'observer'},
  ),
];
